/*
Project: msca
GitHub: https://github.com/MillieFD/msca

BSD 3-Clause License, Copyright (c) 2026, Amelia Fraser-Dale

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the conditions of the LICENSE are met.
*/

//! Core library for the `msca` storage engine.

/* ------------------------------------------------------------------------------ Public Modules */

// TODO → can any submodules be made private to simplify public surface?

pub mod accumulate;
pub mod binary;
pub mod dataset;
pub mod error;
pub mod io;
pub mod manifest;
pub mod query;
pub mod read;
pub mod schema;

/* ------------------------------------------------------------------------------ Public Exports */

// TODO → can any imports be made private to simplify public surface?

pub use memmap2::Mmap;

pub use self::accumulate::{Accumulate, Accumulator, BoxAcc, Columns, Describe, Serialize};
pub use self::binary::Bin;
pub use self::dataset::Dataset;
pub use self::error::Error;
pub use self::io::{Deserialize, Sector, SizedBuf};
pub use self::query::column::{Column, Join, Joiner, Joint};
pub use self::query::Query;
pub use self::read::{Composite, Evaluate, IsOption, Outcome, Read, Reader, Stream};
pub use self::schema::Schema;
pub use self::segment::Align;

/* ----------------------------------------------------------------------------- Private Modules */

mod segment;

/* ----------------------------------------------------------------------------- Private Imports */

use self::schema::number;

/* ----------------------------------------------------------------------- Data Trait Definition */

/// An external type that can be ingested into the [`Dataset`]. Implementations are typically
/// generated by the `#[derive(Data)]` procedural macro.
#[doc = include_str!("../../doc/derive.md")]
pub trait Data: Sized {
    /// Constructs a [`Schema`] describing the layout of [`Self`]; returns a composite type-erased
    /// [`Accumulate`] trait object backed by a heap-allocated growable [`Buffer`][1].
    ///
    /// ### Errors
    ///
    /// Returns [`schema::Error`] if a field name collides with an incompatible existing column.
    ///
    /// [1]: Serialize::Buffer
    fn accumulator(schema: &mut Schema) -> Result<BoxAcc<Self>, schema::Error>;
}
